export type Room = {
    id: number;
    name: string;
    description: string;
    price: string;
    image: string;
    maxGuests?: number;
    rooms?: number | null;
    beds?: number;
    bedType?: string | null;
    bedrooms?: number | null;
    bathrooms?: number | null;
    hasPrivatePool?: boolean;
    hasKitchen?: boolean;
    hasWifi?: boolean;
    hasParking?: boolean;
    hasAC?: boolean;
    checkInTime?: string;
    checkOutTime?: string;
};